name: Build Dev and Upload to Firebase
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          
      - name: Make .gradle directory and set up gradle.properties
        run: |
          mkdir -p ~/.gradle/
          echo android.useAndroidX=true >> ~/.gradle/gradle.properties
          echo kotlin.code.style=official >> ~/.gradle/gradle.properties
          echo android.nonTransitiveRClass=true >> ~/.gradle/gradle.properties
      
      - name: Convert keystore Base64 to File
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore.jks'
          fileDir: './app/'
          encodedString: ${{ secrets.KEYSTORE }}
      
      - name: Copy credentials to global gradle.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: |
          echo KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD >> ~/.gradle/gradle.properties
          echo ALIAS_NAME=$ALIAS_NAME >> ~/.gradle/gradle.properties
          echo ALIAS_PASSWORD=$ALIAS_PASSWORD >> ~/.gradle/gradle.properties
        
      - name: Check gradle.properties
        run: cat ~/.gradle/gradle.properties
        
      - name: Build
        run: ./gradlew build
      
      - name: Assemble Dev
        run: ./gradlew assembleDev
        
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/dev/app-dev.apk
